// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBzcvYpVD6Yg-IKkCOesI_1M1ql1wrF_MY',
    appId: '1:297203425325:web:94b6fc71f13ea90312d8a4',
    messagingSenderId: '297203425325',
    projectId: 'punta-beer',
    authDomain: 'punta-beer.firebaseapp.com',
    storageBucket: 'punta-beer.appspot.com',
    measurementId: 'G-EH34GLS4C8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAAQZPS51V2pz2zKZiadmlVG2Cut8CQ4CQ',
    appId: '1:297203425325:android:9c4cb8a0f866ce1212d8a4',
    messagingSenderId: '297203425325',
    projectId: 'punta-beer',
    storageBucket: 'punta-beer.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9mkCP8x3zCQg5ybTs5m0gyEGFLvSRb6Y',
    appId: '1:297203425325:ios:ee94f9db5160dca112d8a4',
    messagingSenderId: '297203425325',
    projectId: 'punta-beer',
    storageBucket: 'punta-beer.appspot.com',
    iosClientId: '297203425325-du9tean8pcdgplpl4t8b9g8na63qkttn.apps.googleusercontent.com',
    iosBundleId: 'uy.com.puntabeer',
  );
}
